export const OPENCODE_RECONNECT_MIN_MS = 1000;
export const OPENCODE_RECONNECT_MAX_MS = 15000;
export const OPENCODE_SESSION_LOCKED_RETRY_DELAY_MS = 1000;
export const OPENCODE_SESSION_LOCKED_MAX_RETRIES = 3;
