import { worldAssets } from "~/lib/world-assets";

export const houseLayout = {
  ambientDecorations: [
    {
      alpha: 1,
      depth: 320,
      scale: 0.33,
      textureKey: worldAssets.props.desk.key,
      x: 760,
      y: 360,
    },
    {
      alpha: 0.98,
      depth: 260,
      scale: 0.18,
      textureKey: worldAssets.props.shelf.key,
      x: 760,
      y: 180,
    },
    {
      alpha: 1,
      depth: 410,
      scale: 0.2,
      textureKey: worldAssets.props.plant.key,
      x: 1450,
      y: 455,
    },
  ],
  defaultInspectId: "cat-a",
  inspectables: [
    {
      depth: 280,
      description:
        "The House plan lives here: current path, step cadence, and the next visible priority.",
      focusScale: 1.03,
      glowAlpha: 0.28,
      id: "whiteboard",
      meta: "Planning Surface",
      ringScale: null,
      ringX: null,
      ringY: null,
      scale: 0.35,
      shadowAlpha: null,
      shadowScale: null,
      textureKey: worldAssets.props.whiteboard.key,
      title: "Whiteboard",
      x: 280,
      y: 280,
    },
    {
      depth: 360,
      description:
        "A dense little archive of drawers, rolled plans, and pinned scraps that make the work feel durable.",
      focusScale: 1.03,
      glowAlpha: 0.22,
      id: "cabinet",
      meta: "House Archive",
      ringScale: 0.26,
      ringX: 935,
      ringY: 615,
      scale: 0.33,
      shadowAlpha: null,
      shadowScale: null,
      textureKey: worldAssets.props.cabinet.key,
      title: "Cabinet",
      x: 930,
      y: 470,
    },
    {
      depth: 330,
      description:
        "Pinned notices, fresh mail, and items waiting for a human glance collect at this warm little station.",
      focusScale: 1.03,
      glowAlpha: 0.24,
      id: "inbox",
      meta: "Notice Station",
      ringScale: null,
      ringX: null,
      ringY: null,
      scale: 0.28,
      shadowAlpha: null,
      shadowScale: null,
      textureKey: worldAssets.props.inboxStation.key,
      title: "Inbox",
      x: 1240,
      y: 320,
    },
    {
      depth: 660,
      description:
        "Awake, curious, and clearly on-task. Mochi carries the room's active energy without needing a desk-bound animation.",
      focusScale: 1.04,
      glowAlpha: 0.18,
      id: "cat-a",
      meta: "Mochi · Awake",
      ringScale: 0.28,
      ringX: 650,
      ringY: 735,
      scale: 0.22,
      shadowAlpha: 0.34,
      shadowScale: 0.28,
      textureKey: worldAssets.cats.catAAwake.key,
      title: "Mochi",
      x: 650,
      y: 650,
    },
    {
      depth: 620,
      description:
        "Saffron is curled up by the cushion, making the resting state readable from pose alone and keeping the House inhabited.",
      focusScale: 1.04,
      glowAlpha: 0.16,
      id: "cat-b",
      meta: "Saffron · Resting",
      ringScale: 0.22,
      ringX: 255,
      ringY: 610,
      scale: 0.2,
      shadowAlpha: 0.28,
      shadowScale: 0.22,
      textureKey: worldAssets.cats.catBResting.key,
      title: "Saffron",
      x: 255,
      y: 560,
    },
  ],
  panel: {
    accentWidth: 112,
    bodyFontSize: 16,
    descriptionLineSpacing: 6,
    height: 136,
    metaFontSize: 14,
    titleFontSize: 28,
    width: 540,
    x: 768,
    y: 794,
  },
  sceneSize: {
    height: 1024,
    width: 1536,
  },
} as const;
