name: Validate

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bun typecheck

      - run: bun --bun biome check

      - run: bun --bun vitest run --coverage
