name: Validate

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: ${{ github.workflow }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Add matchers
        run: echo "::add-matcher::.github/matchers/tsc.json"
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun --bun tsc --build
      - run: bun --bun biome ci
      - run: bun --bun vitest run --coverage
